services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    restart: always
    hostname: '10.96.20.57'
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://10.96.20.57:9443'
        nginx['ssl_certificate'] = "/etc/gitlab/ssl/gitlab.crt"
        nginx['ssl_certificate_key'] = "/etc/gitlab/ssl/gitlab.key"
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
    ports:
      - 8080:8080
      - 9443:9443
      - 2224:22
    volumes:
      - /config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab
      - ./ssl:/etc/gitlab/ssl
    shm_size: '256m'
    networks:
      - network_test
networks:
  network_test:
    name: network_test
    external: true
